apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: code-llm # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "llm code to SAP AI Core"
    scenarios.ai.sap.com/name: "LLM"
    executables.ai.sap.com/description: "test llm output"
    executables.ai.sap.com/name: "llm-test"
  labels:
    scenarios.ai.sap.com/id: "llm-code"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: credstutorialrepo # your docker registry secret
  entrypoint: myllm
  templates:
  - name: myllm
    steps:
    - - name: llm-test
        template: mycodeblock1

  - name: mycodeblock1
    container:
      image: docker.io/rotin/llm-test:01 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/main.py"
